# Generated by Django 4.1.6 on 2024-05-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_agreed_form_slug_alter_field_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='agreed',
        ),
        migrations.AlterField(
            model_name='field',
            name='identifier',
            field=models.CharField(choices=[('control_input', 'text input'), ('control_email', 'email input'), ('control_phone', 'phone input'), ('control_datetime', 'datetime input'), ('control_dropdown', 'dropdown input')], max_length=20),
        ),
    ]
