# Generated by Django 4.1.6 on 2024-05-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_form_verfiy_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
