# Generated by Django 4.1.6 on 2024-05-06 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_submission_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='verfiy_email',
            new_name='verify_email',
        ),
    ]
