# Generated by Django 4.1.6 on 2024-05-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_rename_verfiy_email_form_verify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
