# Generated by Django 4.1.6 on 2024-06-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_submission_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='identifier',
            field=models.CharField(choices=[('control_input', 'text input'), ('control_email', 'email input'), ('control_phone', 'phone input'), ('control_date', 'date input'), ('control_dropdown', 'dropdown input')], max_length=20),
        ),
    ]
