# Generated by Django 4.1.6 on 2023-03-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessType', models.CharField(max_length=255, verbose_name='Type of Business')),
            ],
        ),
        migrations.CreateModel(
            name='CouponHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254)),
                ('couponCount', models.IntegerField(verbose_name='Current Coupon Count')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('createdBy', models.CharField(max_length=255, null=True, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='DownHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.IntegerField(null=True, verbose_name='from_user id')),
                ('down_user', models.IntegerField(null=True, verbose_name='down_user id')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleType', models.CharField(max_length=255, verbose_name='Type of Role')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('couponCount', models.IntegerField(verbose_name='Current Coupon Count')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.business')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.role')),
            ],
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Coupon Code')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.user')),
            ],
        ),
    ]
