# Generated by Django 4.1.6 on 2023-03-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_completedorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='used',
        ),
        migrations.AlterField(
            model_name='coupons',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Coupon Code'),
        ),
    ]
