# Generated by Django 4.1.6 on 2023-04-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_delete_completedorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jotform_id',
            field=models.TextField(default=True, max_length=30, null=True),
        ),
    ]
