# Generated by Django 4.1.6 on 2023-05-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_alter_user_jotform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leads_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
