# Generated by Django 4.1.6 on 2024-05-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_user_leads_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='couponCount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Current Coupon Count'),
        ),
    ]
