# Generated by Django 4.1.6 on 2024-08-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_alter_user_birthday_alter_user_couponcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
